### PR TITLE
require `cc` 1.0.100 or later

### LINKED ISSUE #1545: Rusqlite 0.32 cannot be compiled with bundled feature
**Problem:**
After upgrading from 0.31 to 0.32, project compilation failed with:
```
    Blocking waiting for file lock on build directory
   Compiling libsqlite3-sys v0.30.0
error[E0308]: mismatched types
   --> /home/egr/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsqlite3-sys-0.30.0/build.rs:267:22
    |
267 |             cfg.flag(format!("-DSQLITE_MAX_VARIABLE_NUMBER={limit}"));
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&str`, found `String`
    |
    = note: this error originates in the macro `format` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> /home/egr/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsqlite3-sys-0.30.0/build.rs:272:22
    |
272 |             cfg.flag(format!("-DSQLITE_MAX_EXPR_DEPTH={limit}"));
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&str`, found `String`
    |
    = note: this error originates in the macro `format` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> /home/egr/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsqlite3-sys-0.30.0/build.rs:277:22
    |
277 |             cfg.flag(format!("-DSQLITE_MAX_COLUMN={limit}"));
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&str`, found `String`
    |
    = note: this error originates in the macro `format` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> /home/egr/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsqlite3-sys-0.30.0/build.rs:286:30
    |
286 |                     cfg.flag(format!("-D{extra}"));
    |                              ^^^^^^^^^^^^^^^^^^^^ expected `&str`, found `String`
    |
    = note: this error originates in the macro `format` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0308`.
error: could not compile `libsqlite3-sys` (build script) due to 4 previous errors
```
bundled feature enabled
```
rusqlite = { version = "0.32", features = ["bundled", "chrono"] }
```
v0.31 are compiled without problem

### PR DESCRIPTION
**Pull request by trevyn**
Closes #1545
xref #1543

Signature of cfg.flag changed in `cc` 1.0.100

I would recommend point releases of both `libsqlite3-sys` and `rusqlite`, and possibly yanking the existing versions.

### CODE REVIEW

**Comment by trevyn** [comment]
Hi gwenn! How is this invalid?

**Comment by gwenn** [comment]
For me, a simple `cargo update` does the same (and eventually `cargo outdated`)...
Because `1.0` and `1.0.100` should be compatible.
For a similar case, see chrono [here](https://deps.rs/repo/github/rusqlite/rusqlite)...
If you don't want to perform a `cargo update` or with `-Z minimal-versions`, that's your choice.

**Comment by trevyn** [comment]
Sorry gwenn, maybe there is a misunderstanding here? If `rusqlite` will not compile with a `cc` less than `1.0.100`, this should be specified as the minimum required version of `cc`?

https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/Dependency.20version.20specification

**Comment by gwenn** [comment]
Let imagine that there is a vulnerability issue in version `1.0.101` of `cc` and a patch is published in `1.0.102`.
I don't expect to need to update its versions in all `Cargo.toml` from `1.0.100` to ``1.0.102`.
So why it should be different for compilation issue ?

**Comment by trevyn** [comment]
It should be different because I, [aegoroff](https://github.com/rusqlite/rusqlite/issues/1545), [nerasse](https://github.com/rusqlite/rusqlite/issues/1543), [hasezoey](https://github.com/tramhao/termusic/pull/352), and presumably CommanderStorm and others have all run into confusing build errors that cargo was designed to automatically resolve, and others will be hit by this going forward.

https://doc.rust-lang.org/cargo/reference/resolver.html#recommendations:

>Try to keep the dependency versions up-to-date with the actual minimum versions that your library requires. For example, if you have a requirement of `bar="1.0.12"`, and then in a future release you start using new features added in the `1.1.0` release of “bar”, update your dependency requirement to `bar="1.1.0"`.
>
>If you fail to do this, it may not be immediately obvious because Cargo can opportunistically choose the newest version when you run a blanket `cargo update`. However, if another user depends on your library, and runs `cargo update your-library`, it will *not* automatically update “bar” if it is locked in their `Cargo.lock`. It will only update “bar” in that situation if the dependency declaration is also updated. Failure to do so can cause confusing build errors for the user using `cargo update your-library`.

**Comment by trevyn** [comment]
Right, I think the way to identify this in CI is with a `-Z minimal-versions` pass. Would you like me to add one?

**Comment by gwenn** [comment]
I would prefer not...

**Comment by thomcc** [comment]
It's probably worth at least fixing this issue, even if there's no CI keeping it up.

**Comment by gwenn** [comment]
Yep, I agree.
But maybe there are others dependencies concerned...
To check, we just need to remove the Cargo.lock locally, do a `cargo update -Z minimal-versions` and then `cargo test --all --all-targets --features bundled-full`
?

**Comment by kpreid** [comment]
`cargo update -Z minimal-versions` will often fail due to dependency specifications you don't control (in your workspace's transitive dependencies). `cargo update -Z direct-minimal-versions` doesn't have this problem because it only affects your workspace's direct dependencies, which you do control.

**Comment by gwenn** [comment]
```
cargo update -Z direct-minimal-versions
    Updating crates.io index
error: failed to select a version for `openssl-sys`.
    ... required by package `libsqlite3-sys v0.30.0 (/Users/gwen/Rust/rusqlite-clean/libsqlite3-sys)`
versions that meet the requirements `^0.9` are: 0.9.0

the package `libsqlite3-sys` depends on `openssl-sys`, with features: `vendored` but `openssl-sys` does not have these features.


failed to select a version for `openssl-sys` which could resolve this conflict
```

**Comment by trevyn** [comment]
https://lib.rs/crates/openssl-sys/versions

Looks like 0.9.35

**Comment by gwenn** [comment]
By lazily taking last versions which cause troubles, `cargo update -Z direct-minimal-versions` and `cargo test --all --all-targets` (idem with `--features bundled`) work with the following changes:
```
diff --git a/Cargo.toml b/Cargo.toml
index 0a20250..ee1d3e9 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -114,9 +114,9 @@ bundled-full = ["modern-full", "bundled"]

 [dependencies]
 time = { version = "0.3.0", features = ["formatting", "macros", "parsing"], optional = true }
-bitflags = "2.0"
+bitflags = "2.6.0"
 hashlink = "0.9"
-chrono = { version = "0.4", optional = true, default-features = false, features = ["clock"] }
+chrono = { version = "0.4.38", optional = true, default-features = false, features = ["clock"] }
 serde_json = { version = "1.0", optional = true }
 csv = { version = "1.1", optional = true }
 url = { version = "2.1", optional = true }
diff --git a/libsqlite3-sys/Cargo.toml b/libsqlite3-sys/Cargo.toml
index f9c3704..0c435a4 100644
--- a/libsqlite3-sys/Cargo.toml
+++ b/libsqlite3-sys/Cargo.toml
@@ -35,16 +35,16 @@ with-asan = []
 wasm32-wasi-vfs = []

 [dependencies]
-openssl-sys = { version = "0.9", optional = true }
+openssl-sys = { version = "0.9.103", optional = true }

 [build-dependencies]
 bindgen = { version = "0.69", optional = true, default-features = false, features = ["runtime"] }
 pkg-config = { version = "0.3.19", optional = true }
-cc = { version = "1.0", optional = true }
-vcpkg = { version = "0.2", optional = true }
+cc = { version = "1.1.6", optional = true }
+vcpkg = { version = "0.2.15", optional = true }
 # for loadable_extension:
-prettyplease = {version = "0.2", optional = true }
+prettyplease = {version = "0.2.20", optional = true }
 # like bindgen
-quote = { version = "1", optional = true, default-features = false }
+quote = { version = "1.0.36", optional = true, default-features = false }
 # like bindgen
-syn = { version = "2.0", optional = true, features = ["full", "extra-traits", "visit-mut"] }
+syn = { version = "2.0.72", optional = true, features = ["full", "extra-traits", "visit-mut"] }
```
But `cargo test --all --all-targets --features bundled-full` fails with `time` crate:
```
error: unexpected token: =
  --> src/types/time.rs:22:13
   |
22 |     version = 2,
   |             ^
```

**Comment by gwenn** [comment]
`cargo test --all --all-targets --features bundled-full` works with these changes:
```diff
diff --git a/Cargo.toml b/Cargo.toml
index 0a20250..4808bd1 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -113,10 +113,10 @@ modern-full = [
 bundled-full = ["modern-full", "bundled"]

 [dependencies]
-time = { version = "0.3.0", features = ["formatting", "macros", "parsing"], optional = true }
-bitflags = "2.0"
+time = { version = "0.3.36", features = ["formatting", "macros", "parsing"], optional = true }
+bitflags = "2.6.0"
 hashlink = "0.9"
-chrono = { version = "0.4", optional = true, default-features = false, features = ["clock"] }
+chrono = { version = "0.4.38", optional = true, default-features = false, features = ["clock"] }
 serde_json = { version = "1.0", optional = true }
 csv = { version = "1.1", optional = true }
 url = { version = "2.1", optional = true }
diff --git a/libsqlite3-sys/Cargo.toml b/libsqlite3-sys/Cargo.toml
index f9c3704..0c435a4 100644
--- a/libsqlite3-sys/Cargo.toml
+++ b/libsqlite3-sys/Cargo.toml
@@ -35,16 +35,16 @@ with-asan = []
 wasm32-wasi-vfs = []

 [dependencies]
-openssl-sys = { version = "0.9", optional = true }
+openssl-sys = { version = "0.9.103", optional = true }

 [build-dependencies]
 bindgen = { version = "0.69", optional = true, default-features = false, features = ["runtime"] }
 pkg-config = { version = "0.3.19", optional = true }
-cc = { version = "1.0", optional = true }
-vcpkg = { version = "0.2", optional = true }
+cc = { version = "1.1.6", optional = true }
+vcpkg = { version = "0.2.15", optional = true }
 # for loadable_extension:
-prettyplease = {version = "0.2", optional = true }
+prettyplease = {version = "0.2.20", optional = true }
 # like bindgen
-quote = { version = "1", optional = true, default-features = false }
+quote = { version = "1.0.36", optional = true, default-features = false }
 # like bindgen
-syn = { version = "2.0", optional = true, features = ["full", "extra-traits", "visit-mut"] }
+syn = { version = "2.0.72", optional = true, features = ["full", "extra-traits", "visit-mut"] }
```
but they are not minimal versions...

**Comment by gwenn** [comment]
> `cargo test --all --all-targets --features bundled-full` works with these changes:
> 
> ```diff
> diff --git a/Cargo.toml b/Cargo.toml
> index 0a20250..4808bd1 100644
> --- a/Cargo.toml
> +++ b/Cargo.toml
> @@ -113,10 +113,10 @@ modern-full = [
>  bundled-full = ["modern-full", "bundled"]
> 
>  [dependencies]
> -time = { version = "0.3.0", features = ["formatting", "macros", "parsing"], optional = true }
> -bitflags = "2.0"
> +time = { version = "0.3.36", features = ["formatting", "macros", "parsing"], optional = true }
> +bitflags = "2.6.0"
>  hashlink = "0.9"
> -chrono = { version = "0.4", optional = true, default-features = false, features = ["clock"] }
> +chrono = { version = "0.4.38", optional = true, default-features = false, features = ["clock"] }
>  serde_json = { version = "1.0", optional = true }
>  csv = { version = "1.1", optional = true }
>  url = { version = "2.1", optional = true }
> diff --git a/libsqlite3-sys/Cargo.toml b/libsqlite3-sys/Cargo.toml
> index f9c3704..0c435a4 100644
> --- a/libsqlite3-sys/Cargo.toml
> +++ b/libsqlite3-sys/Cargo.toml
> @@ -35,16 +35,16 @@ with-asan = []
>  wasm32-wasi-vfs = []
> 
>  [dependencies]
> -openssl-sys = { version = "0.9", optional = true }
> +openssl-sys = { version = "0.9.103", optional = true }
> 
>  [build-dependencies]
>  bindgen = { version = "0.69", optional = true, default-features = false, features = ["runtime"] }
>  pkg-config = { version = "0.3.19", optional = true }
> -cc = { version = "1.0", optional = true }
> -vcpkg = { version = "0.2", optional = true }
> +cc = { version = "1.1.6", optional = true }
> +vcpkg = { version = "0.2.15", optional = true }
>  # for loadable_extension:
> -prettyplease = {version = "0.2", optional = true }
> +prettyplease = {version = "0.2.20", optional = true }
>  # like bindgen
> -quote = { version = "1", optional = true, default-features = false }
> +quote = { version = "1.0.36", optional = true, default-features = false }
>  # like bindgen
> -syn = { version = "2.0", optional = true, features = ["full", "extra-traits", "visit-mut"] }
> +syn = { version = "2.0.72", optional = true, features = ["full", "extra-traits", "visit-mut"] }
> ```
> 
> but they are not minimal versions...

Are you OK with these above changes ?

**Comment by trevyn** [comment]
Fine with me, feel free to close this PR and do that instead, or let me know if you'd prefer I apply them here.
