### ISSUE TITLE
Rusqlite no longer compiles with Rust before v1.77

### ISSUE THREAD

**Issue by nyurik** [rusqlite/rusqlite#1544]
MSRV of rusqlite is now effectively 1.77.2 -- none of the prior compilers would be able to build even the simplest code if that code has `rusqlite = "0.32.0"` as a dependency, otherwise it shows this error. Even though this code is behind the `#[cfg(test)]` attribute.

```
 error[E0658]: `c".."` literals are experimental                                                                                                                                                                                                                  │
│     --> /home/nyurik/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rusqlite-0.32.0/src/lib.rs:1934:44                                                                                                                                                     │
│      |                                                                                                                                                                                                                                                           │
│ 1934 |         let r = unsafe { ffi::sqlite3_open(c":memory:".as_ptr(), &mut handle) };                                                                                                                                                                          │
│      |                                            ^^^^^^^^^^^                                                                                                                                                                                                    │
│      |                                                                                                                                                                                                                                                           │
│      = note: see issue #105723 <https://github.com/rust-lang/rust/issues/105723> for more information                                                                                                                                                            │
│ 
```

Note that I don't mind using latest rustc - but i am not certain if this requirement was intended. Would it make sense to move lib.rs's test code into its own module, e.g

```rust
#[cfg(test)]
mod lib_tests; // Move all tests here
```
