### PR TITLE
Correct pkg-config version

### PR DESCRIPTION
**Pull request by kornelski**
This crate says it works with pkg-config 3.0.0, but it can't:

```
  Compiling pkg-config v0.3.0
error[E0432]: unresolved import `std::fs::PathExt`
  --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/pkg-config-0.3.0/src/lib.rs:60:5
   |
60 | use std::fs::PathExt;
   |     ^^^^^^^^^^^^^^^^ no `PathExt` in `fs`

error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /Users/user/.cargo/registry/src/github.com-1ecc6299db9ec823/pkg-config-0.3.0/src/lib.rs:53:1
   |
53 | #![feature(env, path, unicode, process, fs)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This matters when using `-Z minimal-versions` cargo option.

### CODE REVIEW

**Review by thomcc — APPROVED** [review]
Thanks
