### ISSUE TITLE
Rusqlite 0.32 cannot be compiled with bundled feature

### ISSUE THREAD

**Issue by aegoroff** [rusqlite/rusqlite#1545]
**Problem:**
After upgrading from 0.31 to 0.32, project compilation failed with:
```
    Blocking waiting for file lock on build directory
   Compiling libsqlite3-sys v0.30.0
error[E0308]: mismatched types
   --> /home/egr/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsqlite3-sys-0.30.0/build.rs:267:22
    |
267 |             cfg.flag(format!("-DSQLITE_MAX_VARIABLE_NUMBER={limit}"));
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&str`, found `String`
    |
    = note: this error originates in the macro `format` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> /home/egr/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsqlite3-sys-0.30.0/build.rs:272:22
    |
272 |             cfg.flag(format!("-DSQLITE_MAX_EXPR_DEPTH={limit}"));
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&str`, found `String`
    |
    = note: this error originates in the macro `format` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> /home/egr/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsqlite3-sys-0.30.0/build.rs:277:22
    |
277 |             cfg.flag(format!("-DSQLITE_MAX_COLUMN={limit}"));
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&str`, found `String`
    |
    = note: this error originates in the macro `format` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> /home/egr/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libsqlite3-sys-0.30.0/build.rs:286:30
    |
286 |                     cfg.flag(format!("-D{extra}"));
    |                              ^^^^^^^^^^^^^^^^^^^^ expected `&str`, found `String`
    |
    = note: this error originates in the macro `format` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0308`.
error: could not compile `libsqlite3-sys` (build script) due to 4 previous errors
```
bundled feature enabled
```
rusqlite = { version = "0.32", features = ["bundled", "chrono"] }
```
v0.31 are compiled without problem

**Comment by gwenn** [comment]
https://github.com/rusqlite/rusqlite/issues/1543#issuecomment-2242921603

**Comment by gwenn** [comment]
Version 0.32.1 released.
