### ISSUE TITLE
the trait `FromSql` is not implemented for `Uuid` with "uuid" feature enabled.

### ISSUE THREAD

**Issue by hrsman** [rusqlite/rusqlite#1186]
I am having an issue getting rsuqlite uuid support working in my environment (Windows 10 x64). I am relatively new to Rust so thanks for any help. It seems like my program should at least compile, but the compiler is saying that the FromSql trait is not implemented for uuid::Uuid even though I have the "uuid" feature enabled for rusqlite. I have cloned rusqlite and ran test_uuid with success so I am not sure what the issue is.

Cargo.toml
```
[package]
name = "sqlite_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = { version = "0.27.0", features = [ "bundled", "uuid" ] }
uuid = { version = "1.0"}
r2d2 = "0.8.9"
r2d2_sqlite = "0.20.0"
```

main.rs
```
fn main() {
    println!("Hello, world!");
}

pub type Connection = r2d2::PooledConnection<r2d2_sqlite::SqliteConnectionManager>;
use uuid::Uuid;
fn get_uuid(client: Connection) -> Result<Uuid, rusqlite::Error>{
    let _stmt = "";
    let mut stmt = client.prepare(&_stmt)?;

    stmt.query_row([], |row| {
        Ok(row.get_unwrap::<_,Uuid>(0))
        })
}
```

cargo build output
```
PS > cargo build
   Compiling sqlite_test v0.1.0 (sqlite_test)
error[E0277]: the trait bound `Uuid: FromSql` is not satisfied
   --> src\main.rs:12:16
    |
12  |         Ok(row.get_unwrap::<_,Uuid>(0))
    |                ^^^^^^^^^^ the trait `FromSql` is not implemented for `Uuid`
    |
note: required by a bound in `Row::<'stmt>::get_unwrap`
   --> C:\Users\dev\.cargo\registry\src\github.com-1ecc6299db9ec823\rusqlite-0.27.0\src\row.rs:260:39
    |
260 |     pub fn get_unwrap<I: RowIndex, T: FromSql>(&self, idx: I) -> T {
    |                                       ^^^^^^^ required by this bound in `Row::<'stmt>::get_unwrap`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `sqlite_test` due to previous error
```

**Comment by gwenn** [comment]
Could you please try without `r2d2` ?
=> `r2d2_sqlite` bug / feature(s) not supported
https://github.com/ivanceras/r2d2-sqlite/blob/master/Cargo.toml#L37-L39

**Comment by hrsman** [comment]
Seems to have the same issue without r2d2.

Cargo.toml
```
[package]
name = "sqlite_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = { version = "0.27.0", features = [ "bundled", "uuid" ] }
uuid = { version = "1.0"}
```

main.rs
```
fn main() {
    println!("Hello, world!");
}

use uuid::Uuid;
use rusqlite::Connection;
fn get_uuid(client: Connection) -> Result<Uuid, rusqlite::Error>{
    let _stmt = "";
    let mut stmt = client.prepare(&_stmt)?;

    stmt.query_row([], |row| {
        Ok(row.get_unwrap::<_,Uuid>(0))
        })
}
```

cargo build output
```
PS > cargo build
   Compiling sqlite_test v0.1.0 (sqlite_test)
error[E0277]: the trait bound `Uuid: FromSql` is not satisfied
   --> src\main.rs:12:16
    |
12  |         Ok(row.get_unwrap::<_,Uuid>(0))
    |                ^^^^^^^^^^ the trait `FromSql` is not implemented for `Uuid`
    |
note: required by a bound in `Row::<'stmt>::get_unwrap`
   --> C:\Users\dev\.cargo\registry\src\github.com-1ecc6299db9ec823\rusqlite-0.27.0\src\row.rs:260:39
    |
260 |     pub fn get_unwrap<I: RowIndex, T: FromSql>(&self, idx: I) -> T {
    |                                       ^^^^^^^ required by this bound in `Row::<'stmt>::get_unwrap`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `sqlite_test` due to previous error
```

**Comment by gwenn** [comment]
https://github.com/rusqlite/rusqlite/blob/v0.27.0/Cargo.toml#L120
```
rusqlite = { version="0.27", features = ["bundled", "uuid"] }
uuid = { version = "0.8"}
```
uuid version 0.8 vs 1.0...

**Comment by hrsman** [comment]
@gwenn Thank you for the solution! Could you please explain how you came to that conclusion and why it only works with uuid version 0.8?

**Comment by gwenn** [comment]
I used `cargo tree` to find the issue.
Versions 0.8 and 1.0 are incompatible, right ?
So `uuid::Uuid` version 0.8 and `uuid::Uuid` version 1.0 are distinct types (different compilation units).
And `rusqlite` version 0.27 provides a `FromSql` impl only for `uuid::Uuid` version 0.8.
But your program uses `uuid::Uuid` version 1.0...
